name: Build Renovate configs

on:
  push:
    branches:
      - main
    paths:
      - "renovate/**"
      - package.json
      - pnpm-lock.yaml
      - pnpm-workspace.yaml
      - .github/workflows/build-renovate.yml
  workflow_dispatch:

concurrency:
  group: build-renovate-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: renovate
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm
      - name: Install dependencies & build
        run: pnpm install && pnpm run build:full
      - name: Validate configurations
        if: vars.RENOVATE_SKIP_VALIDATION != 'true'
        run: pnpm run validate
      - name: Push to renovate/${{ github.ref_name }}
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: renovate/${{ github.ref_name }}
          FOLDER: renovate/dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_NAME: github-actions[bot]
          COMMIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          MESSAGE: |
            feat: automated build from commit `{sha}`

            Original commit: {long-sha}

            {msg}
